### ISSUE TITLE
Submitting an empty Bank Account (createBankAccountForm) shows error

### ISSUE THREAD

**Issue by shifas** [PromisePay/promisepay-php#77]
ERROR TypeError: Cannot read property 'BANK_NAME' of undefined
    at Object.validateBankForm (https://js.prelive.promisepay.com/PromisePay.js:1:77489)
    at HTMLFormElement.submitBankEventListener (https://js.prelive.promisepay.com/PromisePay.js:1:75867)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8082/polyfills.js:3045:1), <anonymous>:421:31)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8082/vendor.js:14:1), <anonymous>:4085:33)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8082/polyfills.js:3045:1), <anonymous>:420:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8082/polyfills.js:3045:1), <anonymous>:188:47)
    at ZoneTask.invokeTask [as invoke] (eval at <anonymous> (http://localhost:8082/polyfills.js:3045:1), <anonymous>:495:34)
    at invokeTask (eval at <anonymous> (http://localhost:8082/polyfills.js:3045:1), <anonymous>:1536:14)
    at HTMLFormElement.globalZoneAwareCallback (eval at <anonymous> (http://localhost:8082/polyfills.js:3045:1), <anonymous>:1573:21)
    at .....

**Comment by shifas** [comment]
window.errorStrings may not be set
